# Generated by Django 5.0.7 on 2024-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='offer-banner/')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
