# Generated by Django 5.0.7 on 2024-07-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='facebook',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='insta',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
